baseURL = "/"
languageCode = "en-us"
title = "Typerpc"
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  themeVariant = "blue"
  editURL = "https://github.com/typerpc/typerpc/tree/master/packages/docs"
  author = "Gary Becks <techstar.dev@hotmail.com>"
  # Description of the site, will be used in meta information
  description = "Documentation for typerpc"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = true
  # Disable search function. It will hide search bar
  disableSearch = false
  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = false
  # If set to true, prevents Hugo from including the mermaid module if not needed (will reduce load times and traffic)
  disableMermaid = true
  disableNextPrev = false
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change the title separator. Default to "::".
  titleSeparator = "-"


[Languages]
[Languages.en]
title = "Typerpc Docs"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/typerpc/typerpc"
weight = 10
